#!/bin/bash
#SBATCH --job-name=bgsub_sweep
#SBATCH -n 5
#SBATCH --mem=16000
#SBATCH -p mlow
#SBATCH -o %x_%u_%j.out
#SBATCH -e %x_%u_%j.err

source ~/miniconda3/etc/profile.d/conda.sh
conda activate c6

cd /export/home/group01/C5/oriol/mcv-c6-2026-team1

for i in $(seq 1 5); do
    wandb agent c5-team1/C6-experiment/3npzy3uq --count 10 &
done
wait